import 'package:flutter/material.dart';

const TextTheme lightTextTheme = TextTheme(
  displayLarge: TextStyle(
      fontFamily: 'GerberaBlack',
      color: Colors.black,
      fontWeight: FontWeight.w900),
  displayMedium: TextStyle(
      fontFamily: 'GerberaMedium',
      color: Colors.black,
      fontWeight: FontWeight.w500),
  displaySmall: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.black,
      fontWeight: FontWeight.w400),
  headlineLarge: TextStyle(
      fontFamily: 'GerberaBlack',
      color: Colors.black,
      fontWeight: FontWeight.w900),
  headlineMedium: TextStyle(
      fontFamily: 'GerberaMedium',
      color: Colors.black,
      fontWeight: FontWeight.w500),
  headlineSmall: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.black,
      fontWeight: FontWeight.w400),
  titleLarge: TextStyle(
      fontFamily: 'GerberaBlack',
      color: Colors.black,
      fontWeight: FontWeight.w900),
  titleMedium: TextStyle(
      fontFamily: 'GerberaMedium',
      color: Colors.black,
      fontWeight: FontWeight.w500),
  titleSmall: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.black,
      fontWeight: FontWeight.w400),
  bodyLarge: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.black,
      fontWeight: FontWeight.w400),
  bodyMedium: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.black,
      fontWeight: FontWeight.w400),
  bodySmall: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.black,
      fontWeight: FontWeight.w400),
  labelLarge: TextStyle(
      fontFamily: 'GerberaMedium',
      color: Colors.black,
      fontWeight: FontWeight.w500),
  labelMedium: TextStyle(
      fontFamily: 'GerberaMedium',
      color: Colors.black,
      fontWeight: FontWeight.w500),
  labelSmall: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.black,
      fontWeight: FontWeight.w400),
);

const TextTheme darkTextTheme = TextTheme(
  displayLarge: TextStyle(
      fontFamily: 'GerberaBlack',
      color: Colors.white,
      fontWeight: FontWeight.w900),
  displayMedium: TextStyle(
      fontFamily: 'GerberaMedium',
      color: Colors.white,
      fontWeight: FontWeight.w500),
  displaySmall: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.white,
      fontWeight: FontWeight.w400),
  headlineLarge: TextStyle(
      fontFamily: 'GerberaBlack',
      color: Colors.white,
      fontWeight: FontWeight.w900),
  headlineMedium: TextStyle(
      fontFamily: 'GerberaMedium',
      color: Colors.white,
      fontWeight: FontWeight.w500),
  headlineSmall: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.white,
      fontWeight: FontWeight.w400),
  titleLarge: TextStyle(
      fontFamily: 'GerberaBlack',
      color: Colors.white,
      fontWeight: FontWeight.w900),
  titleMedium: TextStyle(
      fontFamily: 'GerberaMedium',
      color: Colors.white,
      fontWeight: FontWeight.w500),
  titleSmall: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.white,
      fontWeight: FontWeight.w400),
  bodyLarge: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.white,
      fontWeight: FontWeight.w400),
  bodyMedium: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.white,
      fontWeight: FontWeight.w400),
  bodySmall: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.white,
      fontWeight: FontWeight.w400),
  labelLarge: TextStyle(
      fontFamily: 'GerberaMedium',
      color: Colors.white,
      fontWeight: FontWeight.w500),
  labelMedium: TextStyle(
      fontFamily: 'GerberaMedium',
      color: Colors.white,
      fontWeight: FontWeight.w500),
  labelSmall: TextStyle(
      fontFamily: 'GerberaRegular',
      color: Colors.white,
      fontWeight: FontWeight.w400),
);
